### ISSUE TITLE
Display 'total damage' for weapons / spells with multiple damage lines

### ISSUE THREAD

**Issue by pppesky** [dofuslab/dofuslab#125]
![Screenshot 2020-05-07 at 11 49 15](https://user-images.githubusercontent.com/44681146/81286329-ca133680-9058-11ea-9edc-ccda7ea8d5b6.png)

**Comment by lightyearsaway** [comment]
One blocker for this is that there are some spells with multiple damage lines that may not all be applicable, e.g. Devouring Arrow, some Sac spells whose base damage changes based on Suffering.

**Comment by lightyearsaway** [comment]
Done in #160 #169
