### ISSUE TITLE
Cannot set null for non-nullable field Set.name 

### ISSUE THREAD

**Issue by SergioPenal7** [dofuslab/dofuslab#282]
The site dofuslab.io is not loading items seemingly because the error "Cannot set null for non-nullable field Set.name" prompted.

<a href="https://ibb.co/pf1GJHK"><img src="https://i.ibb.co/m9R16ny/error-prompts.jpg" alt="error-prompts" border="0"></a>

**Comment by samlee405** [comment]
fixed with https://github.com/dofuslab/dofuslab/pull/283
