### ISSUE TITLE
Support for custom characteristics

### ISSUE THREAD

**Issue by alexherbo2** [dofuslab/dofuslab#304]

**Comment by lightyearsaway** [comment]
Could you provide more information? What's the use case?

**Comment by alexherbo2** [comment]
For example, when we enhance items with ranged damage, play in team with additional buffs or treats.

**Comment by lightyearsaway** [comment]
![image](https://user-images.githubusercontent.com/27422540/147765850-9f4f0bf7-9e16-487a-9743-31e458829eba.png)

> enhance items with ranged damage

I believe this is already possible with the "mage" interface?

As for buffs, you should be able to add buffs from any class. The only thing missing from that, then, is treats, and maybe we can think about adding those as buffs, but definitely not as common of a use case.
