### ISSUE TITLE
Zoom issue when interacting with inputs on mobile

### ISSUE THREAD

**Issue by pppesky** [dofuslab/dofuslab#96]
When interacting with inputs on mobile, the page zooms in (password change/item search/login) 

![IMG_1396](https://user-images.githubusercontent.com/44681146/80605599-3378c100-8a2b-11ea-825f-8787cc366067.PNG)
![IMG_1397](https://user-images.githubusercontent.com/44681146/80605604-34a9ee00-8a2b-11ea-8fc0-cf392fe90129.PNG)
![IMG_1398](https://user-images.githubusercontent.com/44681146/80605606-34a9ee00-8a2b-11ea-93d5-2987d6e1a1d3.PNG)
![IMG_1395](https://user-images.githubusercontent.com/44681146/80605582-2f4ca380-8a2b-11ea-8d50-dfe6606f9065.PNG)

**Comment by lightyearsaway** [comment]
Expected #101 to fix this but I'm still seeing this on my phone

**Comment by pppesky** [comment]
Hey, reviewed what was said on disc - I think 16px is the way to go. I formualed my thoughts on the Discord but re-posting here for clarity / so we don't lose it

![Screenshot 2020-05-05 at 20 48 37](https://user-images.githubusercontent.com/44681146/81109365-e22c6e00-8f11-11ea-8f03-8b29f61e5ce7.png)
